repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.1.1
  hooks:
    - id: sqlfluff-fix
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
      stages: [commit, push]
    - id: end-of-file-fixer
      stages: [commit, push]
    - id: check-yaml
      args: [--allow-multiple-documents]
      stages: [commit, push]
